# Generated by Django 2.2.6 on 2019-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('firstname', models.CharField(max_length=255)),
                ('middleInitial', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
    ]
