# Generated by Django 2.2.6 on 2019-10-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientGatewayApp', '0002_load_intial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleType', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('quality', models.CharField(max_length=255)),
                ('patientID', models.ForeignKey(db_column='patientId', on_delete=django.db.models.deletion.CASCADE, to='patientGatewayApp.Patient')),
            ],
        ),
    ]
