# Generated by Django 2.2.6 on 2019-10-24 14:17
import os
import json
from sys import path
from patientGatewayApp.models import Sample, Patient
from django.db import migrations

data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../data'))
data_filename = 'samples.json'
data_file = os.path.join(data_dir, data_filename)

def load_data(apps, schema_editor):
    with open(data_file) as json_file:
        data = json.load(json_file)
    for datum in data:
        patient = Patient.objects.get(id=(datum['patientId'] + 1))

        Sample.objects.create(patientID=patient,
                              sampleType=datum['sampleType'],
                              date=datum['date'],
                              quality=datum['quality'])

def unload_data(apps, schema_editor):
    Samples = apps.get_model('patientGatewayApp', 'Sample')
    Samples.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('patientGatewayApp', '0003_auto_20191024_1409'),
    ]

    operations = [
      migrations.RunPython(load_data, reverse_code=unload_data),
    ]
